#-*- mode: org -*-
#+STARTUP: overview 
#+TODO: TODO DONE
* Welcom! Don`t panic!
 _   _   _             _   _   _
| |_| |_| |           | |_| |_| |
 \ _____ /      o_     \ _____ /
  |     |       |_|     |     |
  |  |  |       |       |  |  |
  |   _ } _   _ | _   _ { _   |
  |  | |_| |_| ||| |_| |_| |  |
  |  |                     |  |
  || |                     | ||
  |  |        _____        |  |
  |  |       /_|_|_\       |  |
  |  |      /|_|_|_|\      |  |
  |  |      ||_|_|_||      |  |
  |  |      ||_|_|_||      |  |
  |__|      ||_|_|_||      |__|
 /   |      ||_|_|_||      |   \
=================================
* Pathes
** org files
*** lincks
[[file:~/../Dropbox/orgs/weekly.org][weekly file]]
[[file:~/../Dropbox/orgs/todo_plan.org][ToDo Plan org]]
[[file:~/../Dropbox/orgs/monthly.org][Monthly file]]
[[file:GTD.org][GTD file]]
[[file:today.org][Today org file]]
[[file:~/ORG/gtd/inbox.org][Inbox GTD File]]
[[file:~/ORG/gtd/tickler.org][Tikler Todo File]]

*** main todos
(find-file "D:/Development/lisp/Dropbox/orgs/weekly.org")
(find-file "~/../Dropbox/orgs/todo_main.org")
(find-file "~/../Dropbox/orgs/todo_plan.org")
(find-file "~/../Dropbox/orgs/todo_LongRun.org")

*** uptown todos
файлы для Вышгорода
(find-file "~/../Dropbox/orgs/uptown/todo_rasps.org")
(find-file "~/../Dropbox/orgs/uptown/todo_uplan.org")
*** tools
(find-file-other-frame "~/../Desktop/orgs/capture/Pensieve.org")
*** captures
(find-file-other-frame "~/../Desktop/orgs/capture/Pensieve.org")
(find-file "~/../Desktop/orgs/capture/Pensieve.org")
(find-file-other-frame "~/../Desktop/orgs/capture/astronomicon.org")
(find-file "~/../Desktop/orgs/capture/astronomicon.org")
(find-file-other-frame "~/../Desktop/orgs/capture/emagus.org")
(find-file "~/../Desktop/orgs/capture/emagus.org")
*** gts 
(find-file "~/ORG/gtd/gtd.org")
(find-file "~/ORG/gtd/inbox.org")
(find-file "~/ORG/gtd/tickler.org")
** init files
*** root
(find-file "~/.emacs")
	(find-file "~/INI/init.el")
*** vanila
(find-file "~/INI/inpak.el")
(find-file "~/INI/vanila_cfg.el")
*** Evil
(find-file "~/INI/evil-mod-cfg.el")
	(find-file "~/ELs/Evil/evil-respect-input.el")
	(find-file "~/ELs/Evil/onecharadd.el") not used
	(find-file "~/ELs/Evil/copylines.el") пока нет
*** Orgs
(find-file "~/INI/org-cfg.el")
	(find-file "~/INI/org_agend_cfg.el")
	(find-file "~/INI/babel-cfg.el")
	(find-file "~/ELs/Org/Babel/ob-eshell.el")
*** Folding
(find-file "~/INI/folding-cfg.el")
	(find-file "~/INI/origami_cfg.el") not using
	но содержит в себе огромное количество класных решенией
	которые нужно перенести в outshine-mod
		(find-file "~/ELs/Evil/origami_triplebrase.el")
	(find-file "~/INI/outshine_cfg.el")
*** Other 
(find-file "~/INI/frame-control.el")
(find-file "~/INI/advnsed-selections-cfg.el")
(find-file "~/INI/interface-mods.el")
(find-file "~/INI/hydra-cfg.el")
(find-file "~/INI/www-cfg.el") not used
*** literary 
(find-file "~/INI/lit-cfg.el") not et
	(find-file "~/INI/translate-cfg.el") not et
	(find-file "~/INI/grammer-cfg.el") not et
*** Programing
(find-file "~/INI/dev-cfg.el")
	(find-file "~/INI/autocomplete-cfg.el")
	(find-file "~/INI/snippets-cfg.el")
	(find-file "~/INI/delimiters-cfg.el")
	(find-file "~/INI/js-cfg.el") not used
	(find-file "~/INI/lua-cfg.el")
	(find-file "~/INI/python-cfg.el")
	(find-file "~/INI/c-mode-cfg.el") not used
	(find-file "~/INI/flycheck-cfg.el") 
** exempl
(find-file "~/../hi.txt")
*Help Docs Emacs 
* Команды
** reload init files
(load "~/INI/evil-mod-cfg.el")
(load "~/INI/frame-control.el")
(load "~/INI/vanila_cfg.el")
(load "~/INI/origami_cfg.el")
(load "~/INI/folding-cfg.el")
(load "~/INI/org-cfg.el")
(load "~/INI/lit-cfg.el")
(load "~/INI/dev-cfg.el")
(load "~/INI/interface-mods.el")
(load "~/INI/hydra-cfg.el")
** открыть
(find-file-other-frame "d:/My_Docs/Ofice/PaperFlow/TODO/todo.org")
(org-agenda nil "a")

** Install
tar not found when trying to install from melpa 
You probably have an outdated package database
(package-refresh-contents)
(package-install "company-irony")
** setings
*** systems paths
(setq exec-path (append exec-path '("D:/Development/CPP/CMake/bin/")))
	неменяет системную переменую только переменая емака взятая при запуске
(setenv "PATH" (concat (getenv "PATH") ";c:\\sw\\bin"))
(setq exec-path (append exec-path '("d:/sw/bin")))
	;; example of setting env var named “path”, by appending a new path to existing path

(setenv "PATH"
  (concat
   "C:/cygwin/usr/local/bin" ";"
   "C:/cygwin/usr/bin" ";"
   "C:/cygwin/bin" ";"
   (getenv "PATH")
  )
)
    You can use slash / and you don't have to use backslash \.
    Dir path may end with a path separator /, or without.
    the builtin variable path-separator can be used instead of ;.
;; show env var named path
(getenv "PATH")
*** for Source
(origami-mode)
(outline-minor-mode)
** линкс команды
	 C+c C+o
	[[shell:echo%20"hi%20Max"][Hello?]]
	[[shell:dir][Whera are u?]]
[[
shell:echo "dfgdfg max"
] [
Working?
]]
[[shell:echo "dfgdfg max"][Working?]]

[[shell:echo "dfgdfg max"]
[Working?]]

** Tmp 

(progn

(define-key evil-normal-state-map(kbd "<f2>i") '(lambda() (interactive)
								(org-save-all-org-buffers)
								(save-some-buffers 'no-confirm)
								(evil-normal-state)))

(define-key evil-visual-state-map (kbd "<f7>") '(lambda() (interactive)
	(let ((region-text (buffer-substring (region-beginning) (region-end))))
		(evil-normal-state)
		(query-replace
			region-text
			(read-string (concat "replace("  (current-kill 0 "DO-NOT-MOVE") "):")
						nil
						nil
						(current-kill 0 "DO-NOT-MOVE"))
			))))

(global-set-key(kbd "<f8>") '(lambda() (interactive)
								(save-buffer)
								(evil-normal-state)
								(with-current-buffer "*compilation*"
										(recompile))
								(delete-other-windows)
								))
(global-set-key(kbd "M-<f8>") '(lambda() (interactive)
								(save-buffer)
								(evil-normal-state)
								(compile
								 (read-string
										(concat
											"defult(" (buffer-name) "):")
										(buffer-file-name)
										nil
										(buffer-name)
										)
									)
								))

(define-key evil-normal-state-map "ZF" 'find-file-other-frame)
(define-key evil-normal-state-map "ZH" '(lambda() (interactive)
					(evil-prev-buffer)))
 )
* Help Docs Emacs 
** To set on a file by file 
To set the VisualLineMode on a file by file basis using emacs local variables, try:
    #  local variables:
    #    eval: (visual-line-mode t)
** Keyborde help 
*** evaluate
****    27.9 Evaluating Emacs Lisp Expressions
Emacs Lisp mode is the major mode for editing Emacs Lisp. Its mode command is M-x emacs-lisp-mode.
Emacs provides several commands for evaluating Emacs Lisp expressions. You can use these commands in Emacs Lisp mode, to test your Emacs Lisp code as it is being written. For example, after re-writing a function, you can evaluate the function definition to make it take effect for subsequent function calls. These commands are also available globally, and can be used outside Emacs Lisp mode.
M-:
    Read a single Emacs Lisp expression in the minibuffer, evaluate it, and print the value in the echo area (eval-expression).
~C-x C-e~
    Evaluate the Emacs Lisp expression ~before point~, and print the value in the echo area (eval-last-sexp).
~C-M-x (in Emacs Lisp mode)~
~M-x eval-defun~
    Evaluate the defun containing or after point, and print the value in the echo area (eval-defun).
~M-x eval-region~
    Evaluate all the Emacs Lisp expressions in the region.
~M-x eval-buffer~
    Evaluate all the Emacs Lisp expressions in the buffer. 

M-: (eval-expression) reads an expression using the minibuffer, and evaluates it. (Before evaluating the expression, the current buffer switches back to the buffer that was current when you typed M-:, not the minibuffer into which you typed the expression.)

The command C-x C-e (eval-last-sexp) evaluates the Emacs Lisp expression preceding point in the buffer, and displays the value in the echo area. When the result of an evaluation is an integer, it is displayed together with the value in other formats (octal, hexadecimal, and character if eval-expression-print-maximum-character, described below, allows it).

If M-: or C-x C-e is given a prefix argument, it inserts the value into the current buffer at point, rather than displaying it in the echo area. If the prefix argument is zero, any integer output is inserted together with its value in other formats (octal, hexadecimal, and character). Such a prefix argument also prevents abbreviation of the output according to the variables eval-expression-print-level and eval-expression-print-length (see below). Similarly, a prefix argument of -1 overrides the effect of eval-expression-print-length.

The eval-defun command is bound to C-M-x in Emacs Lisp mode. It evaluates the top-level Lisp expression containing or following point, and prints the value in the echo area. In this context, a top-level expression is referred to as a “defun”, but it need not be an actual defun (function definition). In particular, this command treats defvar expressions specially. Normally, evaluating a defvar expression does nothing if the variable it defines already has a value. But this command unconditionally resets the variable to the initial value specified by the defvar; this is convenient for debugging Emacs Lisp programs. defcustom and defface expressions are treated similarly. Note that the other commands documented in this section do not have this special feature.

With a prefix argument, C-M-x instruments the function definition for Edebug, the Emacs Lisp Debugger. See Instrumenting for Edebug.

The command M-x eval-region parses the text of the region as one or more Lisp expressions, evaluating them one by one. M-x eval-buffer is similar but evaluates the entire buffer.

The options eval-expression-print-level and eval-expression-print-length control the maximum depth and length of lists to print in the result of the evaluation commands before abbreviating them. Supplying a zero prefix argument to eval-expression or eval-last-sexp causes lists to be printed in full. eval-expression-debug-on-error controls whether evaluation errors invoke the debugger when these commands are used; its default is t. eval-expression-print-maximum-character prevents integers which are larger than it from being displayed as characters. 
5.31 How do I execute (“evaluate”) a piece of Emacs Lisp code?
There are a number of ways to execute (evaluate, in Lisp lingo) an Emacs Lisp form:
    If you want it evaluated every time you run Emacs, put it in a file named .emacs in your home directory. This is known as “your .emacs file,” and contains all of your personal customizations.
    You can type the form in the *scratch* buffer, and then type <LFD> (or C-j) after it. The result of evaluating the form will be inserted in the buffer.
    ~In emacs-lisp-mode~, typing ~C-M-x~ evaluates a top-level form before or around point.
    Typing ~C-x C-e~ in ~any buffer~ evaluates the Lisp form immediately before point and prints its value in the echo area.
    Typing M-: or M-x eval-expression allows you to type a Lisp form in the minibuffer which will be evaluated once you press <RET>.
    You can use M-x load-file to have Emacs evaluate all the Lisp forms in a file. (To do this from Lisp use the function load instead.)
    The functions load-library, eval-region, eval-buffer, require, and autoload are also useful; see Emacs Lisp documentation, if you want to learn more about them. 
**** python
***** run unit test
 C-c C-t [elpy-test]

*** get help 
*** get menu command 
    Some of the commands in the menu bar have ordinary key bindings as well;
 if so, a key binding is shown after the item itself. 
To view the full ~command name~ and documentation for a menu item, type ~C-h k~,
 and then select the menu bar with the mouse in the usual way (see Key Help). 
*** coment line 
26.5.1 Comment Commands
The following commands operate on comments:
M-;
    Insert or realign comment on current line; if the region is active, comment or uncomment the region instead (comment-dwim).
~C-x C-;~
    Comment or uncomment the current line (comment-line). If the region is active, comment or uncomment the lines in the region instead.
C-u M-;
    Kill comment on current line (comment-kill).
C-x ;
    Set comment column (comment-set-column).
C-M-j
M-j
    Like <RET> followed by inserting and aligning a comment (comment-indent-new-line). See Multi-Line Comments.
M-x comment-region
C-c C-c (in C-like modes)
    Add comment delimiters to all the lines in the region. 

The command to create or align a comment is M-; (comment-dwim). The word “dwim” is an acronym for “Do What I Mean”; it indicates that this command can be used for many different jobs relating to comments, depending on the situation where you use it.
When a region is active (see Mark), M-; either adds comment delimiters to the region, or removes them. If every line in the region is already a comment, it uncomments each of those lines by removing their comment delimiters. Otherwise, it adds comment delimiters to enclose the text in the region.
If you supply a prefix argument to M-; when a region is active, that specifies the number of comment delimiters to add or delete. A positive argument n adds n delimiters, while a negative argument -n removes n delimiters.
If the region is not active, and there is no existing comment on the current line, M-; adds a new comment to the current line. If the line is blank (i.e., empty or containing only whitespace characters), the comment is indented to the same position where <TAB> would indent to (see Basic Indent). If the line is non-blank, the comment is placed after the last non-whitespace character on the line. Emacs tries to fit the comment between the columns specified by the variables comment-column and comment-fill-column (see Options for Comments), if possible. Otherwise, it will choose some other suitable position, usually separated from the non-comment text by at least one space. In each case, Emacs places point after the comment's starting delimiter, so that you can start typing the comment text right away.
You can also use M-; to align an existing comment. If a line already contains the comment-start string, M-; realigns it to the conventional alignment and moves point after the comment's starting delimiter. As an exception, comments starting in column 0 are not moved. Even when an existing comment is properly aligned, M-; is still useful for moving directly to the start of the comment text.
~C-x C-;~ (comment-line) comments or uncomments complete lines. When a region is active (see Mark), C-x C-; either comments or uncomments the lines in the region. If the region is not active, this command comments or uncomments the line point is on. With a positive prefix argument n, it operates on n lines starting with the current one; with a negative n, it affects n preceding lines. After invoking this command with a negative argument, successive invocations with a positive argument will operate on preceding lines as if the argument were negated.
C-u M-; (comment-dwim with a prefix argument) kills any comment on the current line, along with the whitespace before it. Since the comment is saved to the kill ring, you can reinsert it on another line by moving to the end of that line, doing C-y, and then M-; to realign the comment. You can achieve the same effect as C-u M-; by typing M-x comment-kill (comment-dwim actually calls comment-kill as a subroutine when it is given a prefix argument).
The command M-x comment-region is equivalent to calling M-; on an active region, except that it always acts on the region, even if the mark is inactive. In C mode and related modes, this command is bound to C-c C-c. The command M-x uncomment-region uncomments each line in the region; a numeric prefix argument specifies the number of comment delimiters to remove (negative arguments specify the number of comment delimiters to add).
For C-like modes, you can configure the exact effect of M-; by setting the variables c-indent-comment-alist and c-indent-comments-syntactically-p. For example, on a line ending in a closing brace, M-; puts the comment one space after the brace rather than at comment-column. For full details see Comment Commands. 
*** Rebind keys
**** keys to keys
(global-set-key (kbd "<f7>") (kbd "C-u C-c C-c"))
** Environment Variable 
*** "PATH" : 
**** Описание бага\фичи
	 переменая енворемент обновляется только после перезапуска системы
 тоесть после установки нового софта - он не виден даже после перезапуска емак
 ещё могут быть проблемы посколько есть переменая пути систему
 а есть переменая запуска емака и есть переменая рабочей деректории емака
***** решение:
	  установить инворемнт перемуную в ручную для запушеного еворемента
	  из емака
***** фича
	  есть возможность поексмеремтиовать 
	  если нет уверености что всё настроено как надо
**** setenv "PATH" : 
  ;; example of setting env var named “path”, by appending a new path to existing path
  (setenv "PATH"
	(concat
	 "C:/cygwin/usr/local/bin" ";"
	 "C:/cygwin/usr/bin" ";"
	 "C:/cygwin/bin" ";"
	 (getenv "PATH")
	)
  )
**** getenv "PATH" : 
 (to evaluate elisp code, select it and Alt+x eval-region.
 [see Evaluate Emacs Lisp Code])
	 (getenv "PATH")
**** edit in file
	 copy to *scratch*
(progn
(forward-line 3)
(insert (getenv "PATH"))
)
  (setenv "PATH"
"

"
)
*** SHELL : 
If the path printed by evaluating (getenv "SHELL") in Emacs points at bash
or zsh, this should work fine.
**** getenv : 
(getenv "SHELL")
"D:/Development/lisp/Emacs/libexec/emacs/26.2/x86_64-w64-mingw32/cmdproxy.exe"

*** exec-path
**** Difference between exec-path and PATH
	 The value of environment variable “PATH” is used by emacs when you are running a shell in emacs, similar to when you are using a shell in a terminal.
	 The exec-path is used by emacs itself to find programs it needs for its features, such as spell checking, file compression, compiling, grep, diff, etc.

(when (string-equal system-type "windows-nt")
  (setq exec-path
'(
"C:/Program Files (x86)/Emacs/emacs/bin/"
"C:/Program Files (x86)/Emacs/EmacsW32/gnuwin32/bin/"
"C:/Windows/system32/"
"C:/Windows/"
"C:/Windows/System32/Wbem/"
"C:/Windows/system32/WindowsPowerShell/v1.0/"
)
 ))
**** показать exec-path
(message exec-path)
  (setq exec-path)
**** set
    (setq exec-path (append exec-path '("/sw/bin")))
    (setenv "PATH" (concat (getenv "PATH") ":/sw/bin"))
**** Emacs Lisp Code for Setting PATH and exec-path in sync
(when (string-equal system-type "windows-nt")
  (let (
        (mypaths
         '(
           "C:/Python27"
           ;; "C:/Python32"
           "C:/strawberry/c/bin"
           "C:/strawberry/perl/site/bin"
           "C:/strawberry/perl/bin"

           "C:/Users/h3/AppData/Roaming/npm"
           "C:/Program Files (x86)/nodejs/"

           "C:/cygwin/usr/local/bin"
           "C:/cygwin/usr/bin"
           "C:/cygwin/bin"

           "C:/Program Files (x86)/ErgoEmacs/msys/bin"
           "C:/Program Files (x86)/Mozilla Firefox/"
           "C:/Program Files (x86)/Opera"
           "C:/Program Files (x86)/Safari"
           "C:/Users/h3/AppData/Local/Google/Chrome/Application"
           ) )
        )

    (setenv "PATH" (mapconcat 'identity mypaths ";") )

    (setq exec-path (append mypaths (list "." exec-directory)) )
    ) )
*** Operating System Environment
Emacs provides access to variables in the operating system environment
through various functions.  These variables include the name of the
system, the user’s UID, and so on.
**** Variable: system-configuration
 This variable holds the standard GNU configuration name for the
 hardware/software configuration of your system, as a string.  For
 example, a typical value for a 64-bit GNU/Linux system is
 ‘"x86_64-unknown-linux-gnu"’.
**** Variable: system-type
 The value of this variable is a symbol indicating the type of operating
 system Emacs is running on.  The possible values are:
	We do not wish to add new symbols to make finer distinctions unless it
	is absolutely necessary!  In fact, we hope to eliminate some of these
	alternatives in the future.  If you need to make a finer distinction
	than system-type allows for, you can test
	system-configuration, e.g., against a regexp.
***** aix
  IBM’s AIX.
***** berkeley-unix
   Berkeley BSD and its variants.
***** cygwin
	Cygwin, a Posix layer on top of MS-Windows.
***** 	darwin
	 Darwin (Mac OS X).
***** 	gnu
	 The GNU system (using the GNU kernel, which consists of the HURD and Mach).
***** 	gnu/linux
	 A GNU/Linux system—that is, a variant GNU system, using the Linux
	 kernel.  (These systems are the ones people often call “Linux”, but
	 actually Linux is just the kernel, not the whole system.)
***** 	gnu/kfreebsd
	 A GNU (glibc-based) system with a FreeBSD kernel.
***** 	hpux
	 Hewlett-Packard HPUX operating system.
***** 	irix
	 Silicon Graphics Irix system.
***** 	nacl
	 Google Native Client (NaCl) sandboxing system.
***** 	ms-dos
	 Microsoft’s DOS.  Emacs compiled with DJGPP for MS-DOS binds
	 system-type to ms-dos even when you run it on MS-Windows.
***** 	usg-unix-v
	 AT&T Unix System V.
***** 	windows-nt
	 Microsoft Windows NT, 9X and later.  The value of system-type
	 is always windows-nt, e.g., even on Windows 10.
**** Function: system-name
 This function returns the name of the machine you are running on, as a
 string.
**** User Option: mail-host-address
 If this variable is non-nil, it is used instead of
 system-name for purposes of generating email addresses.  For
 example, it is used when constructing the default value of
 user-mail-address.  See User Identification.  (Since this is
 done when Emacs starts up, the value actually used is the one saved when
 Emacs was dumped.  See Building Emacs.)
**** Command: getenv var &optional frame

 This function returns the value of the environment variable var,
 as a string.  var should be a string.  If var is undefined
 in the environment, getenv returns nil.  It returns
 ‘""’ if var is set but null.  Within Emacs, a list of environment
 variables and their values is kept in the variable process-environment.


 (getenv "USER")
      ⇒ "lewis"


 The shell command printenv prints all or part of the environment:


 bash$ printenv
 PATH=/usr/local/bin:/usr/bin:/bin
 USER=lewis
 TERM=xterm
 SHELL=/bin/bash
 HOME=/home/lewis
 …
**** Command: setenv variable &optional value substitute
 This command sets the value of the environment variable named
 variable to value.  variable should be a string.
 Internally, Emacs Lisp can handle any string.  However, normally
 variable should be a valid shell identifier, that is, a sequence
 of letters, digits and underscores, starting with a letter or
 underscore.  Otherwise, errors may occur if subprocesses of Emacs try
 to access the value of variable.  If value is omitted or
 nil (or, interactively, with a prefix argument), setenv
 removes variable from the environment.  Otherwise, value
 should be a string.

 If the optional argument substitute is non-nil, Emacs
 calls the function substitute-env-vars to expand any
 environment variables in value.

 setenv works by modifying process-environment; binding
 that variable with let is also reasonable practice.

 setenv returns the new value of variable, or nil
 if it removed variable from the environment.
**** Variable: process-environment
 This variable is a list of strings, each describing one environment
 variable.  The functions getenv and setenv work by means
 of this variable.


 process-environment
 => ("PATH=/usr/local/bin:/usr/bin:/bin"
     "USER=lewis"
     "TERM=xterm"
     "SHELL=/bin/bash"
     "HOME=/home/lewis"
     …)


 If process-environment contains multiple elements that
 specify the same environment variable, the first of these elements
 specifies the variable, and the others are ignored.
**** Variable: initial-environment
 This variable holds the list of environment variables Emacs inherited
 from its parent process when Emacs started.
**** Variable: path-separator
 This variable holds a string that says which character separates
 directories in a search path (as found in an environment variable).  Its
 value is ":" for Unix and GNU systems, and ";" for MS systems.
**** Function: parse-colon-path path
 This function takes a search path string such as the value of
 the PATH environment variable, and splits it at the separators,
 returning a list of directory names.  nil in this list means
 the current directory.  Although the function’s name says
 “colon”, it actually uses the value of path-separator.
 (parse-colon-path ":/foo:/bar")
      => (nil "/foo/" "/bar/")
**** Variable: invocation-name
 This variable holds the program name under which Emacs was invoked.  The
 value is a string, and does not include a directory name.
**** Variable: invocation-directory
 This variable holds the directory from which the Emacs executable was
 invoked, or nil if that directory cannot be determined.
**** Variable: installation-directory
 If non-nil, this is a directory within which to look for the
 lib-src and etc subdirectories.  In an installed Emacs,
 it is normally nil.  It is non-nil
 when Emacs can’t find those directories in their standard installed
 locations, but can find them in a directory related somehow to the one
 containing the Emacs executable (i.e., invocation-directory).
**** Function: load-average &optional use-float
 This function returns the current 1-minute, 5-minute, and 15-minute
 system load averages, in a list.  The load average indicates the
 number of processes trying to run on the system.

 By default, the values are integers that are 100 times the system load
 averages, but if use-float is non-nil, then they are
 returned as floating-point numbers without multiplying by 100.

 If it is impossible to obtain the load average, this function signals
 an error.  On some platforms, access to load averages requires
 installing Emacs as setuid or setgid so that it can read kernel
 information, and that usually isn’t advisable.

 If the 1-minute load average is available, but the 5- or 15-minute
 averages are not, this function returns a shortened list containing
 the available averages.


 (load-average)
      ⇒ (169 48 36)
 (load-average t)
      ⇒ (1.69 0.48 0.36)


 The shell command uptime returns similar information.
**** Function: emacs-pid
 This function returns the process ID of the Emacs process,
 as an integer.
**** Variable: tty-erase-char
 This variable holds the erase character that was selected
 in the system’s terminal driver, before Emacs was started.
** Customize 
*** by menu
To customize rainbow-delimiters mode, you can use:
M-x customize-group rainbow-delimiters
Color Scheme

customize-group rainbow-delimiters-faces has the faces for successive nested pairs of delimiters. You can change them through emacs customize or in your color theme or dot-emacs.

The face rainbow-delimiters-unmatched-face is used for unmatched closing delimiters.

Zenburn and Solarized themes have their own colors for these faces.

deftheme/color-theme.el: Further information is at the top of rainbow-delimiters.el.
Stop Highlighting Certain Delimiters

You can disable highlighting of any of the supported delimiter types through the customize interface, in the Toggle Delimiters section. 
*** using command
используя названия из меню можно подобрать подходяшию команду
на основе примера
	;; (custom-theme-set-faces
	;; 'material
	;; `(outline-1 ((t (:height 1.25 :weight bold))))
	;; `(outline-2 ((t (:height 1.15 :weight bold))))
	;; `(outline-3 ((t (:height 1.05 :weight bold))))
	;; `(outline-4 ((t (:height 1.95 :weight bold))))
	;; `(outline-5 ((t (:height 1.85 :weight bold))))
	;; `(outline-6 ((t (:height 1.75 :weight bold))))
	;; `(outline-7 ((t (:height 1.65 :weight bold))))
** info\help
   Check out the info manual for Org Mode with C-h i (info) to learn more, including how to customize the number of days initially displayed and what day your week starts on. 
   удобная систе показиваюшая мануалки по всем установленым модам
** Subprocesses
*** 36.1 Functions that Create Subprocesses
http://ergoemacs.org/emacs_manual/elisp/Shell-Arguments.html#Shell-Arguments
**** three primitives : 
 There are three primitives that create a new subprocess in which to run
 a program.  One of them, ~make-process~, creates an asynchronous
 process and returns a process object (see Asynchronous Processes).
 The other two, =call-process= and =call-process-region=,
 create a synchronous process and do not return a process object
 (see Synchronous Processes).  There are various higher-level
 functions that make use of these primitives to run particular types of
 process.

 Synchronous and asynchronous processes are explained in the following
 sections.  Since the three functions are all called in a similar
 fashion, their common arguments are described here.

 In all cases, the functions specify the program to be run.  An error
 is signaled if the file is not found or cannot be executed.  If the
 file name is relative, the variable exec-path contains a list
 of directories to search.  Emacs initializes exec-path when it
 starts up, based on the value of the environment variable PATH.
 The standard file name constructs, ‘~’, ‘.’, and ‘..’,
 are interpreted as usual in exec-path, but environment variable
 substitutions (‘$HOME’, etc.) are not recognized; use
 substitute-in-file-name to perform them (see File Name Expansion).  nil in this list refers to
 default-directory.

 Executing a program can also try adding suffixes to the specified
 name:
**** User Option: exec-suffixes
  This variable is a list of suffixes (strings) to try adding to the
  specified program file name.  The list should include "" if you
  want the name to be tried exactly as specified.  The default value is
  system-dependent.

  Please note: The argument program contains only the
  name of the program file; it may not contain any command-line
  arguments.  You must use a separate argument, args, to provide
  those, as described below.

  Each of the subprocess-creating functions has a buffer-or-name
  argument that specifies where the output from the program will go.  It
  should be a buffer or a buffer name; if it is a buffer name, that will
  create the buffer if it does not already exist.  It can also be
  nil, which says to discard the output, unless a custom filter
  function handles it.  (See Filter Functions, and Read and Print.)  Normally, you should avoid having multiple processes send
  output to the same buffer because their output would be intermixed
  randomly.  For synchronous processes, you can send the output to a
  file instead of a buffer (and the corresponding argument is therefore
  more appropriately called destination).  By default, both
  standard output and standard error streams go to the same destination,
  but all the 3 primitives allow optionally to direct the standard error
  stream to a different destination.

  All three of the subprocess-creating functions allow to specify
  command-line arguments for the process to run. For call-process
  and call-process-region, these come in the form of a
  &rest argument, args.  For make-process, both the
  program to run and its command-line arguments are specified as a list
  of strings.  The command-line arguments must all be strings, and they
  are supplied to the program as separate argument strings.  Wildcard
  characters and other shell constructs have no special meanings in
  these strings, since the strings are passed directly to the specified
  program.

  The subprocess inherits its environment from Emacs, but you can
  specify overrides for it with process-environment.  See System Environment.  The subprocess gets its current directory from the
  value of default-directory.
**** Variable: exec-directory
  The value of this variable is a string, the name of a directory that
  contains programs that come with GNU Emacs and are intended for Emacs
  to invoke.  The program movemail is an example of such a program;
  Rmail uses it to fetch new mail from an inbox.
**** User Option: exec-path
  The value of this variable is a list of directories to search for
  programs to run in subprocesses.  Each element is either the name of a
  directory (i.e., a string), or nil, which stands for the default
  directory (which is the value of default-directory).
  See executable-find, for the details of this search.


  The value of exec-path is used by call-process and
  start-process when the program argument is not an absolute
  file name.

  Generally, you should not modify exec-path directly.  Instead,
  ensure that your PATH environment variable is set appropriately
  before starting Emacs.  Trying to modify exec-path
  independently of PATH can lead to confusing results.

** Options
*** Visual
*** Home 
**** 3.5 Where do I put my init file?
***** file
On Windows, the .emacs file may be called _emacs for backward compatibility with DOS and FAT filesystems where filenames could not start with a dot. Some users prefer to continue using such a name due to historical problems various Windows tools had in the past with file names that begin with a dot. In Emacs 22 and later, the init file may also be called .emacs.d/init.el. Many of the other files that are created by lisp packages are now stored in the .emacs.d directory too, so this keeps all your Emacs related files in one place.

All the files mentioned above should go in your HOME directory. The HOME directory is determined by following the steps below:

***** environment variable HOME
    If the environment variable HOME is set, use the directory it indicates.
***** registry
    If the registry entry HKCU\SOFTWARE\GNU\Emacs\HOME is set, use the directory it indicates.
    If the registry entry HKLM\SOFTWARE\GNU\Emacs\HOME is set, use the directory it indicates. Not recommended, as it results in users sharing the same HOME directory.
***** if HOME was not set
    If C:\.emacs exists, then use C:/. This is for backward compatibility, as previous versions defaulted to C:/ if HOME was not set.
    Use the user's AppData directory, usually a directory called AppData under the user's profile directory, the location of which varies according to Windows version and whether the computer is part of a domain. 

***** Within Emacs, ~
Within Emacs, ~ at the beginning of a file name is expanded to your HOME directory, so you can always find your .emacs file by typing the command C-x C-f ~/.emacs. 
*** Text Eltments
**** Parenthesis
***** 5.27 How do I show which parenthesis matches the one I’m looking at?
  Call show-paren-mode in your .emacs file:
  (show-paren-mode 1)

  You can also enable this mode by selecting the ‘Paren Match Highlighting’ option from the ‘Options’ menu of the Emacs menu bar at the top of any Emacs frame.

  Alternatives to this mode include:

  If you’re looking at a right parenthesis (or brace or bracket) you can delete it and reinsert it. Emacs will momentarily move the cursor to the matching parenthesis.

  C-M-f (forward-sexp) and C-M-b (backward-sexp) will skip over one set of balanced parentheses, so you can see which parentheses match. (You can train it to skip over balanced brackets and braces at the same time by modifying the syntax table.)

  Here is some Emacs Lisp that will make the % key show the matching parenthesis, like in vi. In addition, if the cursor isn’t over a parenthesis, it simply inserts a % like normal.
  #+BEGIN_SRC elisp
;; By an unknown contributor
(global-set-key "%" 'match-paren)
(defun match-paren (arg)
"Go to the matching paren if on a paren; otherwise insert %."
    (interactive "p")
    (cond ((looking-at "\\s(") (forward-list 1) (backward-char 1))
	    ((looking-at "\\s)") (forward-char 1) (backward-list 1))
	    (t (self-insert-command (or arg 1)))))
  #+END_SRC
** dired
*** запуск dired
** REPL 
** DeBug
** eShell
*** doc
**** commands
***** [so] Is it therefore possible to see what actual elisp is being invoked...
https://emacs.stackexchange.com/questions/14979/access-to-the-elisp-commands-behind-eshell-commands/14981#14981

Yes. They are all located in the eshell folder under Resources/elisp in the Emacs app folder. See screenshot of files on my computer. 


  So I'd like to have the actual elisp...


Open any of those files to see the actual elisp code. For example, ls command with its normal switches is implemented in em-ls.el file by John Wiegley and its core uses expand-file-name function.

How to find which lisp file provides what shell command? Open eshell prompt and then type, say you want to know where kill is in elisp:

which kill


will tell you that 

eshell/kill is a compiled Lisp function in `esh-proc.el'


What other commands are available in eshell?

see the [manual][2]



  there is no way I know of running eshell commands as Babel "code blocks."


There are no special eshell commands per se. Eshell mimics standard unix shell commands using existing lisp functions. You can invoke those same functions in org-babel lisp blocks without any mediating functions implemented in eshell. 
    
***** so find-function
        e.g.: M-x find-function RET eshell/ls RET

I like having find-function bound to C-hC-f as a variant on the standard describe-function binding (via which you can also indirectly get to the code, FYI).

You could also use the following:
#+BEGIN_SRC shell
(defun eshell/goto (name)
  "Visit the source code for the specified eshell command."
  (let ((func (eshell-find-alias-function name)))
    (if func
        (find-function func)
      (error "%s is not an elisp function" name))))
#+END_SRC
$ goto ls


If you want to know what's implemented in elisp and what isn't, you could just ask Emacs to complete on eshell/

e.g.: C-uC-ha eshell/ RET
** Shell
*** Описание 
используется для запуска других процесов
может сильно влиять на работу режимов
поскольку процес может запускатся из eshell
но при этом глючить в шеле
и как результат нечего не будет работать
просто потому что в винде
нужно заменить на чтонить другое
*** explicit-shell-file-name : 
You can start an interactive shell in Emacs by typing M-x shell. 
By default, this will start the standard Windows shell cmd.exe. 
Emacs uses the SHELL environment variable to determine which
program to use as the shell.  To instruct Emacs to use a non-default
shell, you can either set this environment variable, or customize
explicit-shell-file-name.  You can also customize
*** shell-file-name : 
shell-file-name to change the shell that will be used by
subprocesses that are started with shell-command and
related non-interactive shell commands.

"D:/Development/lisp/Emacs/libexec/emacs/26.2/x86_64-w64-mingw32/cmdproxy.exe"
Original value was 
"C:/msys64/home/Administrator/emacs-build/build/emacs-26.2/x86_64/nt/cmdproxy.exe"
*** to git hub
(setq explicit-shell-file-name "d:/Development/version-control.APP/Git/bin/sh.exe")
(setq shell-file-name "sh")
(setq explicit-sh.exe-args '("--noediting" "--login" "-i"))
(setenv "SHELL" shell-file-name)

# (setq explicit-sh.exe-args '("--login" "-i"))
# (add-hook 'comint-output-filter-functions 'comint-strip-ctrl-m)

** Folding 
*** HideShow
Invoke HideShow mode with M-x hs-minor-mode.

* Help Docs eLisp
** show maseges
*** message
(message "Load of init.el is ended")
показывает сообшение прям из проверки
(if nil "yes" "no")
*** format
   (format "sdfsdf")
** varible
*** show type
(type-of chartoadd)
*** chek type
(typep *x* 'integer)
*** chege type 
**** From number to string:
(number-to-string 5)
"5"
you may transform a string to any numerical notation:
(number-to-string 341 :base 10)
"341"
**** From string to number:
(parse-integer "5")
5
with some trash
(parse-integer " 5 something not a number" :junk-allowed t)
5
Or use this:
(read-from-string "23 absd")
23
**** FORMAT 
(format nil "~A" 1)
*** Seeing the Current Value of a Variable
	c-h v
describe-variable

(progn
(evil-open-below 3)
(insert (getenv "PATH"))
)

(describe-variable exec-path)
(symbol-value exec-path)
*** 12.7 Accessing Variable Values determined at run time
https://www.gnu.org/software/emacs/manual/html_node/elisp/Accessing-Variables.html
The usual way to reference a variable is to write the symbol which
names it.  See Symbol Forms.

   Occasionally, you may want to reference a variable which is only
determined at run time.  In that case, you cannot specify the variable
name in the text of the program.  You can use the symbol-value
function to extract the value.


— Function: symbol-value symbol
This function returns the value stored in symbol's value cell. 
This is where the variable's current (dynamic) value is stored.  If
the variable has no local binding, this is simply its global value. 
If the variable is void, a void-variable error is signaled.

        If the variable is lexically bound, the value reported by
symbol-value is not necessarily the same as the variable's
lexical value, which is determined by the lexical environment rather
than the symbol's value cell.  See Variable Scoping.

               (setq abracadabra 5)
               => 5
          (setq foo 9)
               => 9
          
          ;; Here the symbol abracadabra
          ;;   is the symbol whose value is examined.
          (let ((abracadabra 'foo))
            (symbol-value 'abracadabra))
               =>foo
          
          ;; Here, the value of abracadabra,
          ;;   which is foo,
          ;;   is the symbol whose value is examined.
          (let ((abracadabra 'foo))
            (symbol-value abracadabra))
              => 9
          
          (symbol-value 'abracadabra)
              => 5
** Cool guid
https://github.com/chrisdone/elisp-guide
** compile
Emacs 24.3 or below

There's no built-in way of preventing these old files from being loaded, but there are easy ways to get rid of them.

***    You can recompile the entire elpa directory by calling:
   M-x byte-recompile-directory RET ~/.emacs.d/elpa/.
   This should get rid of outdated files.
***    You can use the auto-compile package
and activate auto-compile-on-load-mode which can compile files before they are loaded.

Emacs 24.4

Yes, and it turns out to be rather simple. The
***    load-prefer-newer
variable serves precisely this purpose.

(setq load-prefer-newer t)

Unfortunately, it won't work when some code specifically targets the .elc file, such as (load "server.elc"). But it should be enough as long as you're using requires or calling load without a suffix, which you should.

From the doc:

    load-prefer-newer is a variable defined in lread.c.
    Its value is nil

    Documentation:
    Non-nil means load prefers the newest version of a file.
    This applies when a filename suffix is not explicitly specified and load is trying various possible suffixes (see load-suffixes and load-file-rep-suffixes). Normally, it stops at the first file that exists unless you explicitly specify one or the other. If this option is non-nil, it checks all suffixes and uses whichever file is newest.
    Note that if you customize this, obviously it will not affect files that are loaded before your customizations are read!
* Help Docs Org
** Welcome to Org mode
*** Marker sibols  
 You can make words 
 *bold*, /italic/, _underlined_, =code= and ~verbatim sdfsdfs~, 
 and, if you must, +strike-through+.
*** Lord of the Rings
    My favorite scenes are (in this order)
    1. Eowyn's fight with the witch king
       + this was already my favorite scene in the book
       + I really like Miranda Otto.
    2. The attack of the Rohirrim
    3. Peter Jackson being shot by Legolas
       - on DVD only
       He makes a really funny face when it happens.
    But in the end, no individual scenes matter but the film as a whole.
    Important actors in this film are:
    - Elijah Wood :: He plays Frodo
    - Sean Austin :: He plays Sam, Frodo's friend.  I still remember
      him very well from his role as Mikey Walsh in The Goonies.
** Help
*** info\manual
    Check out the info manual for Org Mode with C-h i (info) to learn more, including how to customize the number of days initially displayed and what day your week starts on. 
    удобная систе показиваюшая мануалки по всем установленым модам
*** links
**** Org Mode - Organize Your Life In Plain Text!
     http://doc.norang.ca/org-mode.html   
     очень последовательнвый манул по всему оргу с кучей примеров
*** мануал пдф
 [[https://orgmode.org/org.pdf][Link to 304p doc about org]]
** Tree Notes 
*** Exempls
  - Note taken on [2018-10-29 Пн 20:19] \\
    ladfdfd
    fdf
    df
    df
    ts add anoser note
    - sdfsdf sdf sdf sdfsd \\
    sdfsdfsdf
    sdfsdf sd fsd fd
    - some note?
	Intrasting where it puting this
    - d
    - sdf
    - sdfsdfsf
    - [X] 
    - [X] sdf
    - 
    - sdfsdfs sdf sdf sd[fn:1] 
    - 
*** Footnotes

[fn:1] The footnote.

[fn:2] Second footnote.
[fn:1] I not undestend ecthakli how this must work
** Help keys
*** Visibility cycling
Tab – show current
S-tab – show all children
C-u C-u C-u Tab – show all including drawers
Startup options
Editting
M-Ret – add element on the same level
M-S-Ret – insert TODO element
M-Right – demote current element
M-S-Right – deomote current subtree
M-Left – promote current element
M-S-Left – promote current subtree
M-S-Up – move current tree up
M-S-Down – move current tree down
C-c C-x C-w – kill current subtree
C-c C-x M-w – copy current subtree
C-c C-x C-y – yank subtree
C-x n s     (org-narrow-to-subtree)
    Narrow buffer to current subtree.
C-x n b     (org-narrow-to-block)
    Narrow buffer to current block.
C-x n w     (widen)
    Widen buffer to remove narrowing.
C-c *     (org-toggle-heading)
    Turn a normal line or plain list item into a headline (so that it becomes a subheading at its location). Also turn a headline into a normal line by removing the stars. If there is an active region, turn all lines in the region into headlines. If the first line in the region was an item, turn only the item lines into headlines. Finally, if the first line is a headline, remove the stars from all headlines in the region. 
*** Plain lists
Use M-Ret to add list item
Ordered list:

    First
    Second
    Third

Unordered lists

    abc
    efg

List with checkboxes (M-S-Ret)

    [ ] First element
    [X] Second element (C-c C-c – toggle checkbox state)
    [X] Third element
*** ToDo functionalityt
C-c C-t – rotate TODO state
S-Left, S-Right – rotate TODO state
**** S-M-Ret – insert new TODO note
(setq org-todo-keywords’((sequence “TODO” “FEEDBACK” “VERIFY” “|” “DONE” “DELEGATED”)))
Footnotes
**** C-c / t     (org-show-todo-tree)

    View TODO items in a sparse tree (see Sparse trees). Folds the entire buffer, but shows all TODO items (with not-DONE state) and the headings hierarchy above them. With a prefix argument (or by using C-c / T), search for a specific TODO. You will be prompted for the keyword, and you can also give a list of keywords like KWD1|KWD2|... to list entries that match any one of these keywords. With a numeric prefix argument N, show the tree for the Nth keyword in the option org-todo-keywords. With two prefix arguments, find all TODO states, both un-done and done. 
**** C-c a t     (org-todo-list)

    Show the global TODO list. Collects the TODO items (with not-DONE states) from all agenda files (see Agenda views) into a single buffer. The new buffer will be in agenda-mode, which provides commands to examine and manipulate the TODO entries from the new buffer (see Agenda commands). See Global TODO list, for more information. 
*** unsort
More devices
C-c C-z – time-stamped drawer

    Note taken on [2013-09-02 Mon 23:54]
    My note here

[fn:2]
 C-c C-x f – footnote[fn:1]**
*** keys add agenda file
   C-c [     (org-agenda-file-to-front)

    Add current file to the list of agenda files. The file is added to the front of the list. If it was already in the list, it is moved to the front. With a prefix argument, file is added/moved to the end. 
C-c ]     (org-remove-file)

    Remove current file from the list of agenda files. 
** template expansion 
*** capture 
**** Template expansion %
10.1.3.2 Template expansion

In the template itself, special “%-escapes”86 allow dynamic insertion of content. The templates are expanded in the order given here:

‘%[FILE]’

    Insert the contents of the file given by FILE.
‘%(EXP)’

    Evaluate Elisp expression EXP and replace it with the result. The EXP form must return a string. Only placeholders pre-existing within the template, or introduced with ‘%[file]’, are expanded this way. Since this happens after expanding non-interactive “%-escapes”, those can be used to fill the expression.
‘%<FORMAT>’

    The result of format-time-string on the FORMAT specification.
‘%t’
    Timestamp, date only.
‘%T’

    Timestamp, with date and time.
‘%u’, ‘%U’

    Like ‘%t’, ‘%T’ above, but inactive timestamps.
‘%i’

    Initial content, the region when capture is called while the region is active. If there is text before ‘%i’ on the same line, such as indentation, and ‘%i’ is not inside a ‘%(exp)’ form, that prefix is added before every line in the inserted text.
‘%a’

    Annotation, normally the link created with org-store-link.
‘%A’

    Like ‘%a’, but prompt for the description part.
‘%l’

    Like ‘%a’, but only insert the literal link.
‘%c’

    Current kill ring head.
‘%x’

    Content of the X clipboard.
‘%k’

    Title of the currently clocked task.
‘%K’

    Link to the currently clocked task.
‘%n’

    User name (taken from user-full-name).
‘%f’

    File visited by current buffer when org-capture was called.
‘%F’

    Full path of the file or directory visited by current buffer.
‘%:keyword’

    Specific information for certain link types, see below.
‘%^g’

    Prompt for tags, with completion on tags in target file.
‘%^G’

    Prompt for tags, with completion all tags in all agenda files.
‘%^t’

    Like ‘%t’, but prompt for date. Similarly ‘%^T’, ‘%^u’, ‘%^U’. You may define a prompt like ‘%^{Birthday}t’.
‘%^C’

    Interactive selection of which kill or clip to use.
‘%^L’

    Like ‘%^C’, but insert as link.
‘%^{PROP}p’

    Prompt the user for a value for property PROP.
‘%^{PROMPT}’

    Prompt the user for a string and replace this sequence with it. You may specify a default value and a completion table with ‘%^{prompt|default|completion2|completion3...}’. The arrow keys access a prompt-specific history.
‘%\N’

    Insert the text entered at the Nth ‘%^{PROMPT}’, where N is a number, starting from 1.
‘%?’

    After completing the template, position point here. 

For specific link types, the following keywords are defined87:
Link type	Available keywords
bbdb	‘%:name’, ‘%:company’
irc	‘%:server’, ‘%:port’, ‘%:nick’
mh, rmail	‘%:type’, ‘%:subject’, ‘%:message-id’
	‘%:from’, ‘%:fromname’, ‘%:fromaddress’
	‘%:to’, ‘%:toname’, ‘%:toaddress’
	‘%:date’ (message date header field)
	‘%:date-timestamp’ (date as active timestamp)
	‘%:date-timestamp-inactive’ (date as inactive timestamp)
	‘%:fromto’ (either “to NAME” or “from NAME”)88
gnus	‘%:group’, for messages also all email fields
w3, w3m	‘%:url’
info	‘%:file’, ‘%:node’
calendar	‘%:date’
org-protocol	‘%:link’, ‘%:description’, ‘%:annotation’
Footnotes
(86)

If you need one of these sequences literally, escape the ‘%’ with a backslash.
(87)

If you define your own link types (see Adding Hyperlink Types), any property you store with org-store-link-props can be accessed in capture templates in a similar way.
(88)
*** structural 
**** list
With just a few keystrokes, it is possible to insert empty structural blocks, such as ‘#+BEGIN_SRC’ … ‘#+END_SRC’, or to wrap existing text in such a block.

C-c C-, (org-insert-structure-template)

    Prompt for a type of block structure, and insert the block at point. If the region is active, it is wrapped in the block. First prompts the user for keys, which are used to look up a structure type from the variable below. If the key is TAB, RET, or SPC, the user is prompted to enter a block type. 

Available structure types are defined in org-structure-template-alist, see the docstring for adding or changing values.

Org Tempo expands snippets to structures defined in org-structure-template-alist and org-tempo-keywords-alist. For example, < s TAB creates a code block. Enable it by customizing org-modules or add ‘(require 'org-tempo)’ to your Emacs init file146.
a	‘#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT’
c	‘#+BEGIN_CENTER’ … ‘#+END_CENTER’
C	‘#+BEGIN_COMMENT’ … ‘#+END_COMMENT’
e	‘#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE’
E	‘#+BEGIN_EXPORT’ … ‘#+END_EXPORT’
h	‘#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’
l	‘#+BEGIN_EXPORT latex’ … ‘#+END_EXPORT’
q	‘#+BEGIN_QUOTE’ … ‘#+END_QUOTE’
s	‘#+BEGIN_SRC’ … ‘#+END_SRC’
v	‘#+BEGIN_VERSE’ … ‘#+END_VERSE’
Footnotes
(146)

For more information, please refer to the commentary section in ‘org-tempo.el’.
**** exempl
	 <s
	 #+BEGIN_SRC 
(setq org-structure-template-alist
      '(("s" "#+BEGIN_SRC ?\n\n#+END_SRC\n")
       ("e" "#+BEGIN_EXAMPLE\n?\n#+END_EXAMPLE\n")
       ("q" "#+BEGIN_QUOTE\n?\n#+END_QUOTE\n")
       ("v" "#+BEGIN_VERSE\n?\n#+END_VERSE\n")
       ("V" "#+BEGIN_VERBATIM\n?\n#+END_VERBATIM\n")))
	 #+END_SRC
in new versin 2.0
(add-to-list 'org-structure-template-alist '("t" . "src translate"))
old
(add-to-list 'org-structure-template-alist '("t" "#+BEGIN_SRC ? translate\n\n#+END_SRC\n"))
<t
	 #+BEGIN_SRC  translate
	Ты работаешь? 
	 #+END_SRC

	 #+RESULTS:
	 : Do you work?

(add-to-list 'org-structure-template-alist '("tr" "#+BEGIN_SRC ? translate :dest ru\n\n#+END_SRC\n"))
	 #+BEGIN_SRC  translate :dest ru
 Do you work?
	 #+END_SRC

	 #+RESULTS:
	 : Вы работаете?
	 
	 
** Tabels
*** exempl
   | freeman | 1 | hucker |
   | max     | 1 | humen  |
   |---------+---+--------|
   |         |   |        |
  
   |---------+---+--------|
   |         |   |        |
*** keys 
**** new
c-c | - generet new table
‘C-c |     (org-table-create-or-convert-from-region)’
**** learn about references is to type C-c ? : 
 Before being able to insert a formula in [Formula], you need to know how to refer to a row, a column or a single field.
The easiest way to learn about references is to type C-c ? while you are in a field.
For example, if you are in the [Formula] field, C-c ? will tell you: line @2, col $4, ref @2$4 or D2, meaning that you are on the second row (or line) of the fourth column, and the reference for this field is either @2$4 or D2. 
**** turn on the reference visualization grid with C-c } : 
At any moment, if you are lost in rows and columns, you can always turn on the reference visualization grid with C-c }: 
**** formula debahen c-c c-{
**** ‘C-c <SPC>     (org-table-blank-field)’
**** ‘M-a     (org-table-beginning-of-field)’
     Move to beginning of the current table field, or on to the previous
     field.
**** ‘M-e     (org-table-end-of-field)’
     Move to end of the current table field, or on to the next field.
     Blank the field at point.
**** move 
‘M-<LEFT>     (org-table-move-column-left)’
‘M-<RIGHT>     (org-table-move-column-right)’
     Move the current column left/right.
‘M-<UP>     (org-table-move-row-up)’
‘M-<DOWN>     (org-table-move-row-down)’
     Move the current row up/down.
**** add \\ remove
‘M-S-<LEFT>     (org-table-delete-column)’
     Kill the current column.
‘M-S-<RIGHT>     (org-table-insert-column)’
     Insert a new column to the left of the cursor position.
‘M-S-<UP>     (org-table-kill-row)’
     Kill the current row or horizontal line.
‘M-S-<DOWN>     (org-table-insert-row)’
**** ‘C-c -     (org-table-insert-hline)’
     Insert a horizontal line below current row.  With a prefix
     argument, the line is created above the current line.
**** ‘C-c <RET>     (org-table-hline-and-move)’
     Insert a horizontal line below current row, and move the cursor
     into the row below that line.
**** ‘C-c ^     (org-table-sort-lines)’
     Sort the table lines in the region.  The position of point
     indicates the column to be used for sorting, and the range of lines
     is the range between the nearest horizontal separator lines, or the
     entire table.  If point is before the first column, you will be
     prompted for the sorting column.  If there is an active region, the
     mark specifies the first line and the sorting column, while point
     should be in the last line to be included into the sorting.  The
     command prompts for the sorting type (alphabetically, numerically,
     or by time).  You can sort in normal or reverse order.  You can
     also supply your own key extraction and comparison functions.  When
     called with a prefix argument, alphabetic sorting will be
     case-sensitive.
**** ‘M-<RET>     (org-table-wrap-region)’
     Split the current field at the cursor position and move the rest to
     the line below.  If there is an active region, and both point and
     mark are in the same column, the text in the column is wrapped to
     minimum width for the given number of lines.  A numeric prefix
     argument may be used to change the number of desired lines.  If
     there is no region, but you specify a prefix argument, the current
     field is made blank, and the content is appended to the field
     above.
**** ‘C-c +     (org-table-sum)’
     Sum the numbers in the current column, or in the rectangle defined
     by the active region.  The result is shown in the echo area and can
     be inserted with ‘C-y’.
**** ‘S-<RET>     (org-table-copy-down)’
     When current field is empty, copy from first non-empty field above.
     When not empty, copy current field down to next row and move cursor
     along with it.  Depending on the option ‘org-table-copy-increment’,
     integer field values will be incremented during copy.  Integers
     that are too large will not be incremented.  Also, a ‘0’ prefix
     argument temporarily disables the increment.  This key is also used
     by shift-selection and related modes (*note Conflicts::).
**** ‘C-c |     (org-table-create-or-convert-from-region)’
     Tables can also be imported by pasting tabular text into the Org
     buffer, selecting the pasted text with ‘C-x C-x’ and then using the
     ‘C-c |’ command (see above under Creation and conversion).
**** C-c = for editing column formulas : 
 If you prefer, you can edit formulas in the minibuffer: use C-c = for editing column formulas or C-u C-c = for field formulas.
**** C-u C-c = for field formulas : 
 If you prefer, you can edit formulas in the minibuffer: use C-c = for editing column formulas or C-u C-c = for field formulas.
**** edit formulas interactively in a dedicated buffer C-c ' 
But you can also edit formulas more interactively in a dedicated buffer by typing C-c '. This new buffer lists all the formulas for the table at point and provides facilities to edit the references.

When the cursor is above a reference, the corresponding field in the table get highlighted. Nice! But you can do more than that: you can actually select the reference by using the S-<left/right/up/down> keys. 
*** Outer exempl
**** GANTT
https://www.youtube.com/watch?time_continue=791&v=5ViUBaarsbw&feature=emb_title
*** formuls 
**** :=vmean($2..$3) 
in this field. This formula means: calculate the mean for fields from the second ($2) to the third ($3) field in this row. If you prefer to use the other notation, type
**** :=vmean(B&..C&)
 where the & character stands for "in this row", which is implicit in the previous notation. 
**** prefixed by = instead of :=  
Note that the only difference with what you've inserted previously is that the formula is prefixed by = instead of :=. When you're done, do a C-c C-c in the field: you should be prompted whether you want to replace the formula with a column formula, which is precisely what we want.

Once you agree with this, the value in the field should be the same than before (namely 11) and you can now update all the fields in this column by reapplying all formulas with C-u C-c * (or C-c C-c if you're on the #+TBLFM line.) 
For now we have been defining formulas by inserting them directly in the table cells: typing = in a field starts the definition for a column formula and typing := starts a definition for a field formula. 
** Tags 
Two: Which tags do you use most?
You can always add tags freely and by hand, but if you configure the most important ones along with fast-access keys, life will be better. Configure the variable org-tags-alist or simply do this right in the file with1
#+TAGS: home(h) work(w) @computer(c) @phone(p) errants(e)
** Todos 
*** Dependantistis 
**** TODO Blocked until (two) is done
***** DONE one
***** TODO two
**** Parent
     :PROPERTIES:
     :ORDERED:  t
     :END:
***** WAITING a
- isdf
- [ ] sdfs
- [X] sdfsdf
***** TODO b, needs to wait for (a)
***** TODO c, needs to wait for (a) and (b)

   You can ensure an entry is never blocked by using the NOBLOCKING property:

**** This entry is never blocked
     :PROPERTIES:
     :NOBLOCKING: t
     :END:

   C-c C-x o     (org-toggle-ordered-property)
*** Status 
  One: More TODO keywords
  Define the TODO states you find useful and single letters for fast selection. Customize the variable org-todo-keywords or simply do this right in the file with1:
  #+TODO: TODO(t) STARTED(s) WAITING(w) | DONE(d) CANCELED(c)
*** arhiv 
    c+c $ 
you can move them to an archive file with C-c $ (org-archive-subtree)отправляет в архи таким путём чистя агенду и лист
момет отправки помечается временени поидееии
и соответственно его скорй всего потом оможно будет от туда выташить и использовать 
*** shadule
    С+с С+s
  Next, we're going to schedule some tasks. Go to a task that you want to do today. Press C-c C-s (org-schedule) and accept the default. Schedule a couple of other tasks for today.

Schedule some tasks for tomorrow, too. This time, when you schedule it, type +1 for the date. You can specify +2 for the day after tomorrow, etc. The 28th? 28. If you want to schedule something for next Saturday, you can type sat. Two Tuesdays from now? 2thu. A month from now? 1m. It's really flexible. 
*** агендa
**** keys add agenda file
    C-c [     (org-agenda-file-to-front)

     Add current file to the list of agenda files. The file is added to the front of the list. If it was already in the list, it is moved to the front. With a prefix argument, file is added/moved to the end. 
 C-c ]     (org-remove-file)

     Remove current file from the list of agenda files. 
**** comands to add agenda file
    (setq org-agenda-files '("~/org"))
    (setq org-agenda-files '("~/ORG/start.org"))
    (setq org-agenda-files (quote ("~/ORG/start.org")))
*** *add a :CATEGORY: property to the top-level, non-TODO heading that identifies the project.  Using your example:

 * Project ABC
  :PROPERTIES:
  :CATEGORY: ABC
  :END:

 ** TODO A task related to Project ABC
 ** TODO Another task related to ABC
 *** TODO Subtask
SCHEDULED: 

In my bog-standard org-mode setup, this results in “ABC” being displayed in the far-left column of the agenda instead of just “todo” (which seems to be the default). This is great — it means that, in the text of the “Subtask” todo entry itself, I don’t need to include a reminder of what project the todo entry is associated with.

Here’s an agenda mockup to illustrate the point, augmented with a “default” entry from my own to-do list:

  todo:       Scheduled:  Follow up on expense reimbursement request
  ABC:        Scheduled:  Subtask

** Links 
*** общее
(define-key global-map "\C-cl" 'org-store-link)
Для того что бы создать ссылку достаточно использовать такой шаблон — [[%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0][описание]].
  [ {] [] ]

Для создания ссылки можно ещё использовать комбинацию C+c C+l. В мини-буфере emacs предложит сначала написать ссылку, затем после нажатия RET — её создать. Находясь в мини-буфере так же можно нажать TAB, для просмотра, какие виды ссылок бывают.
редактировать повторно тойже комбинацией C+c C+l. 

Что бы открыть вновь созданные ссылки необходимо навести точку на ссылку и тыкнуть C+c C+o. Или C+u C+c C+o — если Вы хотите открыть её в другом окне.

Ради интереса, можно перейти в другой файл, нажать там C+c l. И ссылка на этот файл поместится в хранилище ссылок. Перейдя в любой наш файл .org мы можем извлечь из этого хранилища любые сохраненные ссылки, с помощью той же команды C+c C+l.
Самые наблюдательные читатели уже могли заметить, что эта команда как раз и есть та, которую мы вписали в ~/.emacs, в начале.
‘file:/home/dominik/images/jupiter.jpg’ file, absolute path
‘/home/dominik/images/jupiter.jpg’ same as above
‘file:papers/last.pdf’ file, relative path
‘./papers/last.pdf’ same as above
‘file:/ssh:me@some.where:papers/last.pdf’ file, path on remote machine
‘/ssh:me@some.where:papers/last.pdf’ same as above
‘file:sometextfile::NNN’ file, jump to line number
‘file:projects.org’ another Org file
‘file:projects.org::some words’ text search in Org file5
‘file:projects.org::*task title’ heading search in Org file
‘file+sys:/path/to/file’ open via OS, like double-click
‘file+emacs:/path/to/file’ force opening by Emacs
‘docview:papers/last.pdf::NNN’ open in doc-view mode at page
‘id:B7423F4D-2E8A-471B-8810-C40F074717E9’ link to heading by ID
‘mailto:adent@galaxy.net’ mail link
‘irc:/irc.com/#emacs/bob’ IRC link
‘info:org#External links’ Info node link
‘shell:ls *.org’ shell command
‘elisp:org-agenda’ interactive Elisp command
‘elisp:(find-file "Elisp.org")’ Elisp form to evaluate
‘http://www.astro.uva.nl/=dominik’ on the web
*** мануал пдф
[[https://orgmode.org/org.pdf][Link to 304p doc about org]]
*** 4.2 Internal Link
If the link does not look like a URL, it is considered to be internal in the current file.
The most important case is a link like ‘[[#my-custom-id]]’ which links to the entry with
the ‘CUSTOM_ID’ property ‘my-custom-id’. You are responsible yourself to make sure these
custom IDs are unique in a file.
Links such as ‘[[My Target]]’ or ‘[[My Target][Find my target]]’ lead to a text
‘[[My Target]}’ or ‘[[My Target][Find my target]}’
search in the current file.

The link can be followed with C-c C-o when point is on the link, or with a mouse click
(see Section 4.5 [Handling Links], page 39). Links to custom IDs point to the corresponding
headline. The preferred match for a text link is a dedicated target: the same string in double

angular brackets, like ‘<<My Target>>’.
If no dedicated target exists, the link tries to match the exact name of an element within
the buffer. Naming is done with the ‘NAME’ keyword, which has to be put in the line before
the element it refers to, as in the following example
#+NAME: My Target
| a | table |
|----+------------|
| of | four cells |
If none of the above succeeds, Org searches for a headline that is exactly the link text
but may also include a TODO keyword and tags3
1. one item
2. <<target>>another item
Here we refer to item [[target]] \ [[target]} .
The last sentence will appear as ‘Here we refer to item 2’ when exported.
In non-Org files, the search looks for the words in the link text. In the above example
the search would be for ‘target’.
Following a link pushes a mark onto Org’s own mark ring. You can return to the previous
position with C-c &. Using this command several times in direct succession goes back to
positions recorded earlier.
*** 4.7 Link Abbreviations 
[[linkword:tag][description]}
where the tag is optional. The linkword must be a word, starting with a letter, followed by
letters, numbers, ‘-’, and ‘_’. Abbreviations are resolved according to the information in
the variable org-link-abbrev-alist that relates the linkwords to replacement text. Here
is an example:
(setq org-link-abbrev-alist
'(("bugzilla" . "http://10.1.2.9/bugzilla/show_bug.cgi?id=")
("url-to-ja" . "http://translate.google.fr/translate?sl=en&tl=ja&u=%h")
("google" . "http://www.google.com/search?q=")
("gmap" . "http://maps.google.com/maps?q=%s")
("omap" . "http://nominatim.openstreetmap.org/search?q=%s&polygon=1")
("ads" . "https://ui.adsabs.harvard.edu/search/q=%20author%3A\"%s\"")))
If the replacement text contains the string ‘%s’, it is replaced with the tag. Using ‘%h’
instead of ‘%s’ percent-encodes the tag (see the example above, where we need to encode
the URL parameter). Using ‘%(my-function)’ passes the tag to a custom Lisp function,
and replace it by the resulting string.
If the replacement text do not contain any specifier, it is simply appended to the string
in order to create the link.
Instead of a string, you may also specify a Lisp function to create the link. Such a
function will be called with the tag as the only argument.
With the above setting, you could link to a specific bug with ‘[[bugzilla:129]]’,
search the web for ‘OrgMode’ with ‘[[google:OrgMode]]’, show the map location of the
Free Software Foundation ‘[[gmap:51 Franklin Street, Boston]]’

If you need special abbreviations just for a single Org buffer, you can define them in the
file with
#+LINK: bugzilla http://10.1.2.9/bugzilla/show_bug.cgi?id=
#+LINK: google http://www.google.com/search?q=%s
In-buffer completion (see Section 15.1 [Completion], page 228) can be used after ‘[’ to
complete link abbreviations. You may also define a Lisp function that implements special
(e.g., completion) support for inserting such a link with C-c C-l. Such a function should
not accept any arguments, and should return the full link with a prefix. You can set the
link completion function like this:
(org-link-set-parameter "type" :complete #'some-completion-function)
*** 4.8 Search Options in File Links 

[[file:~/code/main.c::255]}
[[file:~/xx.org::My Target]}
[[file:~/xx.org::*My Target]}
[[file:~/xx.org::#my-custom-id]}
[[file:~/xx.org::/regexp/]}
‘255’ Jump to line 255.
‘My Target’
Search for a link target ‘<<My Target>>’, or do a text search for ‘my target’,
similar to the search in internal links, see Section 4.2 [Internal Links], page 36.
In HTML export (see Section 12.9 [HTML Export], page 151), such a file link
becomes a HTML reference to the corresponding named anchor in the linked
file.
‘*My Target’
In an Org file, restrict search to headlines.
‘#my-custom-id’
Link to a heading with a ‘CUSTOM_ID’ property
‘/REGEXP/’
Do a regular expression search for REGEXP. This uses the Emacs command
occur to list all matches in a separate window. If the target file is in Org mode,
org-occur is used to create a sparse tree with the matches.

  As a degenerate case, a file link with an empty file name can be used to search the
current file. For example, ‘[[file:::find me]}’ does a search for ‘find me’ in the current
file, just as ‘[[find me]}’ would.
** сорс комады
*** для всех 
	C+c C+c
(setq org-confirm-babel-evaluate nil)
*** шелл 
 #+BEGIN_SRC sh :shcmd "cmdproxy.exe"
 dir
 #+END_SRC
 #+BEGIN_SRC sh :exports both
 ls
 #+END_SRC

 #+BEGIN_SRC sh :exports both
 ls
 #+END_SRC

*** translate 
**** пример 
  #+BEGIN_SRC translate
  Чтобы поймать психа нужен Псих
  #+END_SRC

  #+RESULTS:
	: To catch psycho Psycho needed

<t
<tr

**** Docs
***** Options
 Each block supports the following arguments:
 Argument	Description	Example	Default
****** :src	Source language.
  +BEGIN_SRC translate :src de	‘auto’ (for auto detection).
****** :dest	Destination language(s).
  +BEGIN_SRC translate :dest it,fr	‘en’ (for English).
  :dest may be a single country-code, or a comma-separated list.
****** All defaults are customizable 
  with M-x customize-group RET ob-translate.
*** Docs
**** 14.1 Structure of code blocks
https://www.gnu.org/software/emacs/manual/html_node/org/Structure-of-code-blocks.html#Structure-of-code-blocks
***** structure source code  : 
Org offers two ways to structure source code in Org documents: in a ‘src’ block, and directly inline. Both specifications are shown below.

A ‘src’ block conforms to this structure:

     #+NAME: <name>
     #+BEGIN_SRC <language> <switches> <header arguments>
       <body>
     #+END_SRC

		 
***** templates system : 
Org mode's templates system (see Easy templates) speeds up creating ‘src’ code blocks with just three keystrokes. Do not be put-off by having to remember the source block syntax. Org also works with other completion systems in Emacs, some of which predate Org and have custom domain-specific languages for defining templates. Regular use of templates reduces errors, increases accuracy, and maintains consistency.

An inline code block conforms to this structure:

     src_<language>{<body>}

or

     src_<language>[<header arguments>]{<body>}

***** Names the ‘src’ block : 
#+NAME: <name>
    Optional. Names the ‘src’ block so it can be called, like a function, from other ‘src’ blocks or inline blocks to evaluate or to capture the results. Code from other blocks, other files, and from table formulas (see The spreadsheet) can use the name to reference a ‘src’ block. This naming serves the same purpose as naming Org tables. Org mode requires unique names. For duplicate names, Org mode's behavior is undefined.
***** mark the start and end : 
#+BEGIN_SRC
#+END_SRC
    Mandatory. They mark the start and end of a block that Org requires. The #+BEGIN_SRC line takes additional arguments, as described next.
<language>
    Mandatory for live code blocks. It is the identifier of the source code language in the block. See Languages, for identifiers of supported languages.
<switches>
    Optional. Switches provide finer control of the code execution, export, and format (see the discussion of switches in Literal examples)
<header arguments>
    Optional. Heading arguments control many aspects of evaluation, export and tangling of code blocks (see Header arguments). Using Org's properties feature, header arguments can be selectively applied to the entire buffer or specific sub-trees of the Org document.
source code, header arguments
<body>
    Source code in the dialect of the specified language identifier. 
**** 14.8.2 Specific header arguments
https://www.gnu.org/software/emacs/manual/html_node/org/Specific-header-arguments.html#Specific-header-arguments
Org comes with many header arguments common to all languages. New header arguments are added for specific languages as they become available for use in ‘src’ code blocks. A header argument is specified with an initial colon followed by the argument's name in lowercase. Common header arguments are:

    var: Pass arguments to ‘src’ code blocks
    results: Specify results type; how to collect
    file: Specify a path for output file
    file-desc: Specify a description for file results
    file-ext: Specify an extension for file output
    output-dir: Specify a directory for output file
    dir: Specify the default directory for code block execution
    exports: Specify exporting code, results, both, none
    tangle: Toggle tangling; or specify file name
    mkdirp: Toggle for parent directory creation for target files during tangling
    comments: Toggle insertion of comments in tangled code files
    padline: Control insertion of padding lines in tangled code files
    no-expand: Turn off variable assignment and noweb expansion during tangling
    session: Preserve the state of code evaluation
    noweb: Toggle expansion of noweb references
    noweb-ref: Specify block's noweb reference resolution target
    noweb-sep: String to separate noweb references
    cache: Avoid re-evaluating unchanged code blocks
    sep: Delimiter for writing tabular results outside Org
    hlines: Handle horizontal lines in tables
    colnames: Handle column names in tables
    rownames: Handle row names in tables
    shebang: Make tangled files executable
    tangle-mode: Set permission of tangled files
    eval: Limit evaluation of specific code blocks
    wrap: Mark source block evaluation results
    post: Post processing of results of code block evaluation
    prologue: Text to prepend to body of code block
    epilogue: Text to append to body of code block 

For language-specific header arguments, see Languages. 

**** 14.10 Noweb reference syntax
https://www.gnu.org/software/emacs/manual/html_node/org/Noweb-reference-syntax.html#Noweb-reference-syntax
***** Org supports named blocks in Noweb style syntax.
For Noweb literate programming details, see http://www.cs.tufts.edu/~nr/noweb/).

			 <<code-block-name>>

	For the header argument :noweb yes, Org expands Noweb style references in the ‘src’ code block before evaluation.

	For the header argument :noweb no, Org does not expand Noweb style references in the ‘src’ code block before evaluation.

	The default is :noweb no. Org defaults to :noweb no so as not to cause errors in languages where Noweb syntax is ambiguous. Change Org's default to :noweb yes for languages where there is no risk of confusion.

	Org offers a more flexible way to resolve Noweb style references (see noweb-ref).

	Org can include the results of a code block rather than its body. To that effect, append parentheses, possibly including arguments, to the code block name, as show below.

			 <<code-block-name(optional arguments)>>

	Note that when using the above approach to a code block's results, the code block name set by #+NAME keyword is required; the reference set by :noweb-ref will not work.

 
***** example : 
 Here is an example that demonstrates how the exported content changes when Noweb style references are used with parentheses versus without.

 With:

			#+NAME: some-code
			#+BEGIN_SRC python :var num=0 :results output :exports none
			print(num*10)
			#+END_SRC

 this code block:

			#+BEGIN_SRC text :noweb yes
			<<some-code>>
			#+END_SRC

 expands to:

			print(num*10)

			
***** with parentheses : 
 Below, a similar Noweb style reference is used, but with parentheses, while setting a variable num to 10:

			#+BEGIN_SRC text :noweb yes
			<<some-code(num=10)>>
			#+END_SRC

 Note that now the expansion contains the results of the code block some-code, not the code block itself:

			100

 For faster tangling of large Org mode files, set org-babel-use-quick-and-dirty-noweb-expansion variable to t. The speedup comes at the expense of not correctly resolving inherited values of the :noweb-ref header argument. 
**** 14.11 Key bindings and useful functions
https://www.gnu.org/software/emacs/manual/html_node/org/Key-bindings-and-useful-functions.html#Key-bindings-and-useful-functions
Many common Org mode key sequences are re-bound depending on the context.
***** Active key bindings in code blocks:

 C-c C-c 	org-babel-execute-src-block
 C-c C-o 	org-babel-open-src-block-result
 M-<UP> 	org-babel-load-in-session
 M-<DOWN> 	org-babel-switch-to-session
***** Active key bindings in Org mode buffer:

	C-c C-v p or C-c C-v C-p 	org-babel-previous-src-block
	C-c C-v n or C-c C-v C-n 	org-babel-next-src-block
	C-c C-v e or C-c C-v C-e 	org-babel-execute-maybe
	C-c C-v o or C-c C-v C-o 	org-babel-open-src-block-result
	C-c C-v v or C-c C-v C-v 	org-babel-expand-src-block
	C-c C-v u or C-c C-v C-u 	org-babel-goto-src-block-head
	C-c C-v g or C-c C-v C-g 	org-babel-goto-named-src-block
	C-c C-v r or C-c C-v C-r 	org-babel-goto-named-result
	C-c C-v b or C-c C-v C-b 	org-babel-execute-buffer
	C-c C-v s or C-c C-v C-s 	org-babel-execute-subtree
	C-c C-v d or C-c C-v C-d 	org-babel-demarcate-block
	C-c C-v t or C-c C-v C-t 	org-babel-tangle
	C-c C-v f or C-c C-v C-f 	org-babel-tangle-file
	C-c C-v c or C-c C-v C-c 	org-babel-check-src-block
	C-c C-v j or C-c C-v C-j 	org-babel-insert-header-arg
	C-c C-v l or C-c C-v C-l 	org-babel-load-in-session
	C-c C-v i or C-c C-v C-i 	org-babel-lob-ingest
	C-c C-v I or C-c C-v C-I 	org-babel-view-src-block-info
	C-c C-v z or C-c C-v C-z 	org-babel-switch-to-session-with-code
	C-c C-v a or C-c C-v C-a 	org-babel-sha1-hash
	C-c C-v h or C-c C-v C-h 	org-babel-describe-bindings
	C-c C-v x or C-c C-v C-x 	org-babel-do-key-sequence-in-edit-buffer

* Help Docs Gnus
  The Emacs news and email reader.
* Help Docs Mods 
** use-package
*** Getting started
;; This is only needed once, near the top of the file
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  (add-to-list 'load-path "<path where use-package is installed>")
  (require 'use-package))

(use-package foo)
This loads in the package foo, but only if foo is available on your system. If not, a warning is logged to the *Messages* buffer.
*** :init :config
Use the :init keyword to execute code before a package is loaded. It accepts one or more forms, up to the next keyword:

(use-package foo
  :init
  (setq foo-variable t))
Similarly, :config can be used to execute code after a package is loaded. In cases where loading is done lazily (see more about autoloading below), this execution is deferred until after the autoload occurs:

(use-package foo
  :init
  (setq foo-variable t)
  :config
  (foo-mode 1))
As you might expect, you can use :init and :config together:

(use-package color-moccur
  :commands (isearch-moccur isearch-all)
  :bind (("M-s O" . moccur)
         :map isearch-mode-map
         ("M-o" . isearch-moccur)
         ("M-O" . isearch-moccur-all))
  :init
  (setq isearch-lazy-highlight t)
  :config
  (use-package moccur-edit))
In this case, I want to autoload the commands isearch-moccur and isearch-all from color-moccur.el, and bind keys both at the global level and within the isearch-mode-map (see next section). When the package is actually loaded (by using one of these commands), moccur-edit is also loaded, to allow editing of the moccur buffer.
*** Key-binding
Another common thing to do when loading a module is to bind a key to primary commands within that module:

(use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))
This does two things: first, it creates an autoload for the ace-jump-mode command and defers loading of ace-jump-mode until you actually use it. Second, it binds the key C-. to that command. After loading, you can use M-x describe-personal-keybindings to see all such keybindings you've set throughout your .emacs file.

A more literal way to do the exact same thing is:

(use-package ace-jump-mode
  :commands ace-jump-mode
  :init
  (bind-key "C-." 'ace-jump-mode))
When you use the :commands keyword, it creates autoloads for those commands and defers loading of the module until they are used. Since the :init form is always run -- even if ace-jump-mode might not be on your system -- remember to restrict :init code to only what would succeed either way.

The :bind keyword takes either a cons or a list of conses:

(use-package hi-lock
  :bind (("M-o l" . highlight-lines-matching-regexp)
         ("M-o r" . highlight-regexp)
         ("M-o w" . highlight-phrase)))
The :commands keyword likewise takes either a symbol or a list of symbols.

NOTE: inside strings, special keys like tab or F1-Fn have to be written inside angle brackets, e.g. "C-<up>". Standalone special keys (and some combinations) can be written in square brackets, e.g. [tab] instead of "<tab>". The syntax for the keybindings is similar to the "kbd" syntax: see https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html for more information.

Examples:

(use-package helm
  :bind (("M-x" . helm-M-x)
         ("M-<f5>" . helm-find-files)
         ([f10] . helm-buffers-list)
         ([S-f10] . helm-recentf)))
Furthermore, remapping commands with :bind and bind-key works as expected, because when the binding is a vector, it is passed straight to define-key. So the following example will rebind M-q (originally fill-paragraph) to unfill-toggle:

(use-package unfill
  :bind ([remap fill-paragraph] . unfill-toggle))
*** Binding to keymaps
Normally :bind expects that commands are functions that will be autoloaded from the given package. However, this does not work if one of those commands is actually a keymap, since keymaps are not functions, and cannot be autoloaded using Emacs' autoload mechanism.

To handle this case, use-package offers a special, limited variant of :bind called :bind-keymap. The only difference is that the "commands" bound to by :bind-keymap must be keymaps defined in the package, rather than command functions. This is handled behind the scenes by generating custom code that loads the package containing the keymap, and then re-executes your keypress after the first load, to reinterpret that keypress as a prefix key.

For example:

(use-package projectile
  :bind-keymap
  ("C-c p" . projectile-command-map))
Binding within local keymaps

Slightly different from binding a key to a keymap, is binding a key within a local keymap that only exists after the package is loaded. use-package supports this with a :map modifier, taking the local keymap to bind to:

(use-package helm
  :bind (:map helm-command-map
         ("C-c h" . helm-execute-persistent-action)))
The effect of this statement is to wait until helm has loaded, and then to bind the key C-c h to helm-execute-persistent-action within Helm's local keymap, helm-mode-map.

Multiple uses of :map may be specified. Any binding occurring before the first use of :map are applied to the global keymap:

(use-package term
  :bind (("C-c t" . term)
         :map term-mode-map
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)
         :map term-raw-map
         ("M-o" . other-window)
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)))
*** Modes and interpreters
Similar to :bind, you can use :mode and :interpreter to establish a deferred binding within the auto-mode-alist and interpreter-mode-alist variables. The specifier to either keyword can be a cons cell, a list of cons cells, or a string or regexp:

(use-package ruby-mode
  :mode "\\.rb\\'"
  :interpreter "ruby")

;; The package is "python" but the mode is "python-mode":
(use-package python
  :mode ("\\.py\\'" . python-mode)
  :interpreter ("python" . python-mode))
If you aren't using :commands, :bind, :bind*, :bind-keymap, :bind-keymap*, :mode, :interpreter, or :hook (all of which imply :defer; see the docstring for use-package for a brief description of each), you can still defer loading with the :defer keyword:

(use-package ace-jump-mode
  :defer t
  :init
  (autoload 'ace-jump-mode "ace-jump-mode" nil t)
  (bind-key "C-." 'ace-jump-mode))
This does exactly the same thing as the following:

(use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))
*** Magic handlers

Similar to :mode and :interpreter, you can also use :magic and :magic-fallback to cause certain function to be run if the beginning of a file matches a given regular expression. The difference between the two is that :magic-fallback has a lower priority than :mode. For example:

(use-package pdf-tools
  :load-path "site-lisp/pdf-tools/lisp"
  :magic ("%PDF" . pdf-view-mode)
  :config
  (pdf-tools-install :no-query))
This registers an autoloaded command for pdf-view-mode, defers loading of pdf-tools, and runs pdf-view-mode if the beginning of a buffer matches the string "%PDF".

*** Hooks

The :hook keyword allows adding functions onto hooks, here only the basename of the hook is required. Thus, all of the following are equivalent:

(use-package ace-jump-mode
  :hook prog-mode)

(use-package ace-jump-mode
  :hook (prog-mode . ace-jump-mode))

(use-package ace-jump-mode
  :commands ace-jump-mode
  :init
  (add-hook 'prog-mode-hook #'ace-jump-mode))
And likewise, when multiple hooks should be applied, the following are also equivalent:

(use-package ace-jump-mode
  :hook (prog-mode text-mode))

(use-package ace-jump-mode
  :hook ((prog-mode text-mode) . ace-jump-mode))

(use-package ace-jump-mode
  :hook ((prog-mode . ace-jump-mode)
         (text-mode . ace-jump-mode)))

(use-package ace-jump-mode
  :commands ace-jump-mode
  :init
  (add-hook 'prog-mode-hook #'ace-jump-mode)
  (add-hook 'text-mode-hook #'ace-jump-mode))
The use of :hook, as with :bind, :mode, :interpreter, etc., causes the functions being hooked to implicitly be read as :commands (meaning they will establish interactive autoload definitions for that module, if not already defined as functions), and so :defer t is also implied by :hook.
*** Conditional loading
**** :if
You can use the :if keyword to predicate the loading and initialization of modules.
For example, I only want edit-server running for my main, graphical Emacs, not for other Emacsen I may start at the command line:

(use-package edit-server
  :if window-system
  :init
  (add-hook 'after-init-hook 'server-start t)
  (add-hook 'after-init-hook 'edit-server-start t))
In another example, we can load things conditional on the operating system:

(use-package exec-path-from-shell
  :if (memq window-system '(mac ns))
  :ensure t
  :config
  (exec-path-from-shell-initialize))
**** :disable
The :disabled keyword can turn off a module you're having difficulties with, or stop loading something you're not using at the present time:

(use-package ess-site
  :disabled
  :commands R)
When byte-compiling your .emacs file, disabled declarations are omitted from the output entirely, to accelerate startup times.
**** :when
NOTE: :when is provided as an alias for :if, and :unless foo means the same thing as :if (not foo). For example, the following will also stop :ensure from happening on Mac systems:

(when (memq window-system '(mac ns))
  (use-package exec-path-from-shell
    :ensure t
    :config
    (exec-path-from-shell-initialize)))
Conditional loading before :preface

If you need to conditionalize a use-package form so that the condition occurs before even the :preface is executed, simply use when around the use-package form itself:
*** Loading packages in sequence
Sometimes it only makes sense to configure a package after another has been loaded, because certain variables or functions are not in scope until that time. This can achieved using an :after keyword that allows a fairly rich description of the exact conditions when loading should occur. Here is an example:

(use-package hydra
  :load-path "site-lisp/hydra")

(use-package ivy
  :load-path "site-lisp/swiper")

(use-package ivy-hydra
  :after (ivy hydra))
In this case, because all of these packages are demand-loaded in the order they occur, the use of :after is not strictly necessary. By using it, however, the above code becomes order-independent, without an implicit depedence on the nature of your init file.

By default, :after (foo bar) is the same as :after (:all foo bar), meaning that loading of the given package will not happen until both foo and bar have been loaded. Here are some of the other possibilities:

:after (foo bar)
:after (:all foo bar)
:after (:any foo bar)
:after (:all (:any foo bar) (:any baz quux))
:after (:any (:all foo bar) (:all baz quux))
When you nest selectors, such as (:any (:all foo bar) (:all baz quux)), it means that the package will be loaded when either both foo and bar have been loaded, or both baz and quux have been loaded.

NOTE: pay attention if you set use-package-always-defer to t, and also use the :after keyword, as you will need to specify how the declared package is to be loaded: e.g., by some :bind. If you're not using one of tho mechanisms that registers autoloads, such as :bind or :hook, and your package manager does not provide autoloads, it's possible that without adding :demand t to those declarations, your package will never be loaded.

*** Prevent loading if dependencies are missing

While the :after keyword delays loading until the dependencies are loaded, the somewhat simpler :requires keyword simply never loads the package if the dependencies are not available at the time the use-package declaration is encountered. By "available" in this context it means that foo is available if (featurep 'foo) evaluates to a non-nil value. For example:

(use-package abbrev
  :requires foo)
This is the same as:

(use-package abbrev
  :if (featurep 'foo))
As a convenience, a list of such packages may be specified:

(use-package abbrev
  :requires (foo bar baz))
For more complex logic, such as that supported by :after, simply use :if and the appropriate Lisp expression.
*** Gathering Statistics

If you'd like to see how many packages you've loaded, what stage of initialization they've reached, and how much aggregate time they've spent (roughly), you can enable use-package-compute-statistics after loading use-package but before any use-package forms, and then run the command M-x use-package-report to see the results. The buffer displayed is a tabulated list. You can use S in a column to sort the rows based on it.
*** (use-package-chords)
The :chords keyword allows you to define key-chord bindings for use-package declarations in the same manner as the :bind keyword.

To enable the extension:

(use-package use-package-chords
  :ensure t
  :config (key-chord-mode 1))
Then you can define your chord bindings in the same manner as :bind using a cons or a list of conses:

(use-package ace-jump-mode
  :chords (("jj" . ace-jump-char-mode)
           ("jk" . ace-jump-word-mode)
           ("jl" . ace-jump-line-mode)))
*** Some timing results
On my Retina iMac, the "Mac port" variant of Emacs 24.4 loads in 0.57s, with around 218 packages configured (nearly all of them lazy-loaded). However, I experience no loss of functionality, just a bit of latency when I'm first starting to use Emacs (due to the autoloading). Since I also use idle-loading for many packages, perceived latency is typically reduced overall.

On Linux, the same configuration loads in 0.32s.

If I don't use Emacs graphically, I can test the absolute minimum times. This is done by running:

time emacs -l init.elc -batch --eval '(message "Hello, world!")'
On the Mac I see an average of 0.36s for the same configuration, and on Linux 0.26s.
*** DONE use-package
	CLOSED: [2019-09-13 Пт 05:52]


The easiest way is to install use-package.

(package-initialize)
(require 'package)
(add-to-list 'package-archives
    '("melpa" . "http://melpa.milkbox.net/packages/") t)

(dolist (package '(use-package))
   (unless (package-installed-p package)
       (package-install package)))

Then

 (use-package paredit
   :ensure t)

The :ensure t is what ensures that the package is installed.

To just load ensure multiple packages are install

(dolist (package '(package-a package-b package-c))
 (unless (package-installed-p package)
   (package-install package))
   (require package))))
** hidra mod 
    https://github.com/abo-abo/hydra
This is a package for GNU Emacs that can be used to tie related commands into a family of short bindings with a common prefix - a Hydra.
** DONE WindMove & FrameMove 
	 CLOSED: [2019-08-06 Вт 05:49]
https://truthseekers.io/lessons/an-introduction-to-emacs-everything-you-need-to-know-to-get-started/
;; Remap windmove keys to home keys
(global-set-key (kbd "M-h") 'windmove-left)
(global-set-key (kbd "M-j") 'windmove-down)
(global-set-key (kbd "M-k") 'windmove-up)
(global-set-key (kbd "M-l") 'windmove-right)
